"""Step 5 TDD — fanout.py: generate_agent_learned_md + fanout_agent_learned."""
from __future__ import annotations

import threading
from pathlib import Path

import pytest

from agent_learner.core.fanout import (
    FanoutResult,
    generate_agent_learned_md,
    fanout_agent_learned,
)
from agent_learner.core.lifecycle import LearningLifecycle
from agent_learner.core.models import LearningRule
from agent_learner.core.storage import canonical_learning_root, global_learning_root, resolve_learning_root


def _promote_rule(tmp_path, name="test-rule", **kwargs):
    root = resolve_learning_root(Path(tmp_path))
    lc = LearningLifecycle(root)
    rule = LearningRule(
        name=name, rule="test rule text", why="test why",
        scope="project", good_pattern="good", avoid_pattern="bad",
        **kwargs,
    )
    lc.promote(rule)


class TestGenerateMd:
    def test_empty_rules(self, tmp_path):
        content = generate_agent_learned_md(tmp_path)
        assert "auto-generated" in content
        assert "##" not in content.split("auto-generated")[1]  # no rule sections

    def test_with_approved_rule(self, tmp_path):
        _promote_rule(tmp_path, name="my-rule")
        content = generate_agent_learned_md(tmp_path)
        assert "## my-rule" in content
        assert "test rule text" in content

    def test_header_format(self, tmp_path):
        content = generate_agent_learned_md(tmp_path)
        assert content.startswith("<!-- agent-learned.md — auto-generated by agent-learner v2. do not edit. -->")


class TestFanout:
    def test_writes_source_file(self, tmp_path):
        _promote_rule(tmp_path)
        result = fanout_agent_learned(tmp_path)
        source = tmp_path / ".agent-learner" / "agent-learned.md"
        assert source.exists()
        assert result.written >= 1

    def test_writes_to_inject_dirs(self, tmp_path):
        _promote_rule(tmp_path)
        dir1 = tmp_path / "d1"
        dir2 = tmp_path / "d2"
        result = fanout_agent_learned(tmp_path, inject_dirs=[str(dir1), str(dir2)])
        assert (dir1 / "agent-learned.md").exists()
        assert (dir2 / "agent-learned.md").exists()
        assert result.written == 3  # source + 2 dirs

    def test_skips_identical_content(self, tmp_path):
        _promote_rule(tmp_path)
        result1 = fanout_agent_learned(tmp_path)
        source = tmp_path / ".agent-learner" / "agent-learned.md"
        mtime1 = source.stat().st_mtime
        # Same content, should skip
        import time; time.sleep(0.05)
        result2 = fanout_agent_learned(tmp_path)
        mtime2 = source.stat().st_mtime
        assert mtime1 == mtime2  # file not rewritten

    def test_partial_failure_continues(self, tmp_path):
        _promote_rule(tmp_path)
        # Create a dir that's read-only to force write failure
        bad_dir = tmp_path / "readonly"
        bad_dir.mkdir()
        bad_dir.chmod(0o444)
        try:
            result = fanout_agent_learned(tmp_path, inject_dirs=[str(bad_dir)])
            assert result.failed >= 1
            # Source still written
            assert (tmp_path / ".agent-learner" / "agent-learned.md").exists()
        finally:
            bad_dir.chmod(0o755)  # restore for cleanup

    def test_default_inject_dirs_from_config(self, tmp_path):
        _promote_rule(tmp_path)
        # No inject_dirs specified, should default to [".agent-learner"]
        result = fanout_agent_learned(tmp_path)
        assert result.written >= 1

    def test_concurrent_write_lock(self, tmp_path):
        _promote_rule(tmp_path)
        errors = []

        def write():
            try:
                fanout_agent_learned(tmp_path)
            except Exception as e:
                errors.append(e)

        threads = [threading.Thread(target=write) for _ in range(5)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        assert errors == []

    def test_result_has_correct_counts(self, tmp_path):
        _promote_rule(tmp_path, name="r1")
        _promote_rule(tmp_path, name="r2")
        result = fanout_agent_learned(tmp_path)
        assert result.rules_included == 2


class TestFanoutResult:
    def test_defaults(self):
        r = FanoutResult()
        assert r.written == 0
        assert r.failed == 0
        assert r.rules_included == 0
        assert r.errors == []
