"""Generate and fan-out agent-learned.md to configured directories."""
from __future__ import annotations

import json
import threading
from dataclasses import dataclass, field
from pathlib import Path

from .lifecycle import LearningLifecycle
from .storage import canonical_learning_root

_LOCK = threading.Lock()

_HEADER = "<!-- agent-learned.md — auto-generated by agent-learner v2. do not edit. -->"


@dataclass(slots=True)
class FanoutResult:
    written: int = 0
    failed: int = 0
    rules_included: int = 0
    errors: list[str] = field(default_factory=list)


def _resolve_inject_dirs(project_root: Path) -> list[str]:
    config_path = project_root / ".agent-learner" / "config.json"
    if config_path.exists():
        try:
            data = json.loads(config_path.read_text(encoding="utf-8"))
            dirs = data.get("inject_dirs")
            if dirs:
                return dirs
        except (json.JSONDecodeError, OSError):
            pass
    return [".agent-learner"]


def generate_agent_learned_md(project_root: Path) -> str:
    """Generate the agent-learned.md content from approved rules."""
    root = canonical_learning_root(project_root)
    lc = LearningLifecycle(root)
    try:
        rules = lc.list_rules(statuses=["approved"])
    except Exception:
        rules = []

    lines = [_HEADER, "", "# Learned Rules", ""]

    for rule in rules:
        lines.append(f"## {rule.name}")
        lines.append(rule.rule)
        lines.append(f"**Why**: {rule.why}")
        meta_parts = [f"scope: {rule.scope}"]
        if rule.validated_on_models:
            meta_parts.append(f"validated: {', '.join(rule.validated_on_models)}")
        lines.append(f"*{' | '.join(meta_parts)}*")
        lines.append("")

    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    """Write content to path only if it differs. Returns True if written."""
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
            if existing == content:
                return False
        except OSError:
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def fanout_agent_learned(
    project_root: Path,
    inject_dirs: list[str] | None = None,
) -> FanoutResult:
    """Generate agent-learned.md and fan-out to all inject directories."""
    with _LOCK:
        return _fanout_inner(project_root, inject_dirs)


def _fanout_inner(
    project_root: Path,
    inject_dirs: list[str] | None,
) -> FanoutResult:
    result = FanoutResult()
    content = generate_agent_learned_md(project_root)

    root = canonical_learning_root(project_root)
    lc = LearningLifecycle(root)
    try:
        rules = lc.list_rules(statuses=["approved"])
        result.rules_included = len(rules)
    except Exception:
        pass

    if inject_dirs is None:
        inject_dirs = _resolve_inject_dirs(project_root)

    # Always write source
    source_path = project_root / ".agent-learner" / "agent-learned.md"
    if _write_if_changed(source_path, content):
        result.written += 1

    # Fan-out to inject_dirs
    for d in inject_dirs:
        target = Path(d)
        if not target.is_absolute():
            target = project_root / target
        target_file = target / "agent-learned.md"
        try:
            if _write_if_changed(target_file, content):
                result.written += 1
        except OSError as e:
            result.failed += 1
            result.errors.append(f"{target_file}: {e}")

    return result
